### ISSUE TITLE
Common fields as csv

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sigils#100]
Since we´re trying to describe all fields with a certain CSV format, i think we should do the same for the fields in README.md, section "Common Index Fields".

**Comment by dicortazar** [comment]
Common index fields are the same in the indexes than in the CSV files.
Does it work if I modify the sentence from "Following fields that should be included in any index pattern:" to "Following fields that should be included in any index pattern and CSV files schemas:"?

If there are other needs to be added to the README, please open a pull request.

**Comment by jgbarah** [comment]
I'm sorry, I think I didn't explain well my suggestion. What I intended to say is that, given that we're using CSV files to describe all indexes, we could also have a CSV description for the common part of all the indexes, so that it is not ambiguous.

This description could be used in addition to, or instead of, the description of the same fields in all the files.

**Comment by alpgarcia** [comment]
This should be part of https://github.com/chaoss/grimoirelab-elk/tree/master/grimoire_elk as we moved CSVs there. 

As a reminder, we made that decision to have index documentation near to the code that creates those indices.
