### ISSUE TITLE
Gerrit panels uses name and it must use author_name

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-sigils#156]
In the Gerrit panel for measuring the number of authors, in the metric visualization the field used is `author_uuid`, which is correct. But in the submitters table, the field used for bucketing the authors is `name` (Descending), which is not correct. It must be `author_name` to be in sync with the metrics vis. And in general, the author information must come from SortingHat, the fields starting with `author_`.

**Comment by alpgarcia** [comment]
Waiting for #159 reviews. Issue should be solved with that change.
