### ISSUE TITLE
[documentation] Ask description for each field in data schema

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sigils#166]
[Data schemas](https://github.com/chaoss/grimoirelab-sigils/tree/master/schema) are very useful to understand which data is GrimoireLab producing.

Wouldn't it be nice to have a short description for each field to make easier to understand what it represents?

A possible way to to do that would be to add a new column with just that description in the .csv file

**Comment by alpgarcia** [comment]
Schemas are not part of this project anymore. This issue should be moved to https://github.com/chaoss/grimoirelab-elk/issues

**Comment by jsmanrique** [comment]
Ok, I can close #166 and open a new one there. Thanks

**Comment by alpgarcia** [comment]
Thanks!
