### ISSUE TITLE
Panels customization docs are related with Bitergia Analytics dashboards, not GrimoireLab

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sigils#171]
Current [panels customization docs](https://github.com/chaoss/grimoirelab-sigils/blob/master/doc/dashboard-customization.md) are focus o how Bitergia customers can customize their panels.

Wouldn't it be nice if it were focus on how GrimoireLab users can
1. customize existing panels?
2. create new panels?
3. reference new panes in the side bar menu?

**Comment by alpgarcia** [comment]
I agree. We would need to move current documentation to Bitergia's GitLab and start building new docs.

> 3. reference new panes in the side bar menu?
I fear this is related with Kibiter.

**Comment by jgbarah** [comment]
> I agree. We would need to move current documentation to Bitergia's GitLab and start building new docs.

You mean writing new docs here?

**Comment by alpgarcia** [comment]
> You mean writing new docs here?

Yes, I do, as far as we don't have information for community but for customers (I'm talking about customizing panels related document only). 

We have something explaining how to export modified panels in [CONTRIBUTING.md](https://github.com/chaoss/grimoirelab-sigils/blob/master/CONTRIBUTING.md). I don't know if having our own documentation on panel customization makes sense or just pointing to official Kibana documentation would be more appropriate.

**Comment by alpgarcia** [comment]
Closing it as documentation has been modified and these docs are currently not available.
 Via https://github.com/chaoss/grimoirelab-sigils/pull/427
