### ISSUE TITLE
Create some doc to guide people about how to create panels

### ISSUE THREAD

**Issue by dicortazar** [chaoss/grimoirelab-sigils#190]
The goal of this task is to specify the usual process we follow to create widgets or panels.

There are at least three steps that comes to my mind:
* Creation of searches. This helps to produce final widgets as tables, or to be later used by other widgets to visualize subsets of the original index pattern.
* Creation of widgets. Those might be created on top of a Search of filtering the information directly in the widget with specific filters.
* Creation of panels. This is an aggregation of panels.

And some guidelines:
* Use donuts instead of full pie charts
* Try to create a panel that does not need any scroll
* Try to create widgets without scrolling (this may happen in tables).

PR related: #188

**Comment by harveyr-gh** [comment]
Hi @dicortazar @valeriocos first off, I hope you are doing all right during the COVID situation. Secondly, GrimoireLab is awesome. I'm running it on a mac after following this tutorial:
https://chaoss.community/blog-post/2019/10/08/simplifying-how-to-install-grimoirelab/

I just have the default dashboards git and github running, so I've only touched the main setup.cfg and projects.json so far.

I'm hoping to add "github-pull-requests-comments-and-collaboration" and "github-issues-comments-and-collaboration" and have cloned the grimoirelab-sigils repo, but unsure what to do next. Do I run setup.sh, and then modify my main grimoirelab files somehow? I'm not asking for full documentation, but was hoping for a bit of help to add those dashboards.

Thanks in advance!
Ryan

**Comment by valeriocos** [comment]
Hi @harveyr-gh ,

Thank you for your interest in GrimoireLab!

If I understand correctly, you would like to see in your instance the dashboards "github-pull-requests-comments-and-collaboration" and "github-issues-comments-and-collaboration". If this is the case, you need to enable the param `github-comments` in the `panels` section within the setup.cfg (https://github.com/chaoss/grimoirelab-sirmordred#panels) and restart the docker-compose.

If you like to play with code, you can try to use [kidash](https://github.com/chaoss/grimoirelab-kidash). Install it from the source code, and import the dashboards and the index patterns (https://github.com/chaoss/grimoirelab-kidash#usage).

Let me know how it goes and don't hesitate to write if need help!

**Comment by harveyr-gh** [comment]
Thanks @valeriocos for the quick reply. For some reason mordred is failing after I add that, the mordred log says:

`Starting two workers: collect and update tasks
Error while consuming configuration: ('Wrong section param:', 'panels', 'github-comments')`

My setup.cfg looks like this after the change:
`[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
github-comments = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = XXXX
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched

[github2:pull]
api-token = XXXX
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
category = pull_request

[github2:issue]
api-token = XXXX
#enterprise-url = <YOUR_GITHUB_ENTERPRISE_URL>
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched`

The relevant section in projects.json is:
`"maya-usd": {
      "git": [
          "https://github.com/Autodesk/maya-usd.git"
      ],
      "github": [
          "https://github.com/Autodesk/maya-usd"
      ],
      "github2:pull": [
          "https://github.com/Autodesk/maya-usd"
      ],
      "github2:issue": [
          "https://github.com/Autodesk/maya-usd"
      ]
 },`

**Comment by valeriocos** [comment]
Hi @harveyr-gh ,

The problem you have is due to an old version of grimoirelab declared in the docker-compose. Now the version is updated (sorry for the inconvenience).

These are the conf files I used:
**projects.json**
```
{
  "maya-usd": {
    "git": [
      "https://github.com/Autodesk/maya-usd.git"
    ],
    "github": [
      "https://github.com/Autodesk/maya-usd"
    ],
    "github2:pull": [
      "https://github.com/Autodesk/maya-usd"
    ],
    "github2:issue": [
      "https://github.com/Autodesk/maya-usd"
    ]
  }
}
```

**setup.cfg**

Please note that the name of the indexes should be different
```
[github]
api-token = xxx
raw_index = github_demo_raw <---
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched <---

[github2:pull]
api-token = xxx
raw_index = github2_pull_demo_raw <---
sleep-for-rate = true
sleep-time = "300"
enriched_index = github2_pull_demo_enriched <---
category = pull_request

[github2:issue]
api-token = xxx
raw_index = github2_issue_demo_raw <---
sleep-for-rate = true
sleep-time = "300"
enriched_index = github2_issue_demo_enriched <---
```

Let me know if this solves your problem.

**Comment by harveyr-gh** [comment]
Thanks @valeriocos! I'll try this tomorrow.
As a side-note, I think I noticed a small typo in the docs:
https://github.com/chaoss/grimoirelab-sirmordred#panels

"github-comments (bool: False): Enable GitHub comments menu. Note that if enabled, the github2:issue and github2:pulls sections in the setup.cfg and projects.json should be declared"

I think it's meant to say "github2:pull" instead of "github2:pulls"?

Cheers,
Ryan

**Comment by valeriocos** [comment]
> Thanks @valeriocos! I'll try this tomorrow.

You're welcome @harveyr-gh !

> I think it's meant to say "github2:pull" instead of "github2:pulls"?

Good catch! Would you like to submit a PR to fix the typo?

**Comment by harveyr-gh** [comment]
@valeriocos the dashboard with collaboration data works on my end now, thanks again!

For the typo, sure: I have the change ready, but when I push I'm getting "Permission to chaoss/grimoirelab-sirmordred.git denied to harveyr-gh".

**Comment by valeriocos** [comment]
great! you're welcome @harveyr-gh !

You cannot direct push to that repo, you can either:
- fork the sirmordred repo, create a branch, add you change and then push it to your fork. GitHub will detect it and will allow you to open a PR
- you can edit the file directly from github (I have never tried, so I'm not sure if you can do it in the original repo or in your fork). 
![captura_299](https://user-images.githubusercontent.com/6515067/77770864-36584e80-7046-11ea-8ce5-0292d58e841c.png)

**Comment by harveyr-gh** [comment]
Cool, the PR is here: https://github.com/chaoss/grimoirelab-sirmordred/pull/446

Thanks for your patience. Cheers.

**Comment by valeriocos** [comment]
Thank you for your contribution @harveyr-gh ! If you want put your hands on GrimoireLab, consider to follow the Getting Started at: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md

In case you want to share your experience with GrimoireLab and help other users, please consider to add a Q&A at: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#how-to- (If you need some inspiration for Q&As, here you can find a short list:  https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_panels.py)

Thanks again!

**Comment by dicortazar** [comment]
emm I think I'm late to the conversation :). @harveyr-gh @valeriocos thanks ;)

**Comment by alpgarcia** [comment]
Closing this in favor of a more focused one: #467

For future conversations, imho this thread is not talking about sigils at all and another issue should be opened probably in sirmordred to continue the conversation there.
