### ISSUE TITLE
Use directories instead of branches for different versions of the panels

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sigils#219]
Right now, panels for Kibana5 and Kibana6 are in different branches in git. Instead of that, I think having them in different directories would be better, and would scale better for the future.

Having different directories allows for the pip package of panels (or anyone cloning the repo) to have available in a single checkout all the panels, and then decide which version they want to use. This could be easily done with the option of kidash to upload a certain directory, or with a new version to select a collection (each collection could be a directory).

In the future, if we decide to have different "collections" (eg, panels for a certain kind of use), we could just open a new directory.

In any case, we can still have the "default collection" in a certain directory. This would be uploaded by kidash by default.

If you want, I could send a pr with all of this.

**Comment by acs** [comment]
With this approach, with tools like kidash we can support the importing of panels from different versions, which is a better scenario than now. We need to modify a bit the tools to support it, but I like it.

**Comment by alpgarcia** [comment]
Closing this because we finally decided to keep only those panels that are currently being maintained in master branch. Legacy panels would be stored in other branches.

As we are moving towards having collections of panels, we should discuss this when deciding how to distribute those collections.
