### ISSUE TITLE
[chaoss-gmd][code_development] Build a panel for Pull Request Merged

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#299]
CHAOSS GMD working group has defined several metrics related to [code development efficiency](https://github.com/chaoss/wg-gmd/blob/89d4067112f81bda145e73fbed661a1266d7b6b4/focus_areas/code_development/goal_code_development.md)

Taking `Pull Request Merged` metric definition from there, build a panel around this metric. Ideally, this panel should contain:
* No more than 5 widgets, to avoid overwhelming the user.
* A markdown widget below with some basic explanations about what we are looking at.

Efficiency panels can be used as an example of the structure we would like to follow:
https://github.com/chaoss/grimoirelab-sigils/blob/master/doc/gerrit-review-efficiency.md

**Comment by alpgarcia** [comment]
I started getting some data from Sigils repository using GrimoireLab chain against GitHub. Then I checked PR #297 to see if we can find those PRs closed that were merged, but not identified as merges by GitHub UI. The answer is NO. 

Thus, as a workaround in GitHub (it also could apply to other similar sources) I rely on Git index instead.

To identify Merges we can use a filter like:
`title:Merge* OR files:0`

The bad part is this is not always correct to identify 100% of merges. The good part is that we can modify it live in the panels. To do it I created a search, so by modifying the search we can update all the panels except those built with Timelion, that needs to be manually updated. Another option could be using the query string in the panel to perform the search. I'm open to other approaches as well. Please vote for yours :)

A first version of this panel looks like:
![captura de pantalla de 2018-11-27 16-38-48](https://user-images.githubusercontent.com/3502941/49092786-0c7cf500-f263-11e8-98ef-d8ae04f3c8ba.png)

I've also opened #300 to let you try the panel if needed (using kidash to import it is needed).
```
kidash -g -e https://xxx:xxxx@localhost:9200 --import git-index-pattern.json
kidash -g -e https://xxx:xxxx@localhost:9200 --import pull_requests_merged.json
``` 
I'll update this PR once #296 is ready and we have a working directory structure for collections. I'll try to include contribution guidelines there, explaining how to get data and import panels locally as I did to build this panel. In the meantime, suggestions and help are welcome. If somebody wants to create panels for another metrics, feel free to do it, just try to follow/improve a similar layout and conditions mentioned in issue description.

**Comment by alpgarcia** [comment]
I'll follow @GeorgLink proposal to include, at least, the following information for each panel:
```
I think the following information would be good to include consistently:
- Name (title of blog post).
- Screenshot.
- When was it created by whom?
- What version of GrimoireLab was it built for?
- What does it display (list of metrics)?
- Why was it built and what is it used for?
```

**Comment by alpgarcia** [comment]
We could use a Front Matter like the following:
```
---
title: Community Structure
description: find who are your core, regular and casual contributors.
author: John Doe
created_at: 2018-12-05 (YYYY-MM-DD)
grimoirelab_version: 0.2.1
layout: panel
---
```
MD document should contain at least:
* What does it display (list of metrics)?
* Why was it built and what is it used for?
* Screenshot.

I've updated `CONTRIBUTING.md` file accordingly, please see #304. It is still under testing and review, so feel free to comment whatever you want.

Note: I'm using `title` instead of `name` because using name didn't work when used in a collection loop.

**Comment by GeorgLink** [comment]
Thanks @alpgarcia. That seems to translate well.

**Comment by dicortazar** [comment]
As this ticket follows PR #306 and this has been already merged, I'll close this one.

Thanks to all of you for commenting here and adding value, it's great!

If you feel that this tickets should be re-opened, please feel free to do so.
