### ISSUE TITLE
Create GitLab efficiency panels

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-sigils#302]
Similar to GitHub and [Gerrit](https://github.com/chaoss/grimoirelab-sigils/blob/master/doc/gerrit-review-efficiency.md) efficiency panels, we need to create GitLab panels.

These panels should follow these guidelines:
* No more than 5 widgets, to avoid overwhelming the user.
 * A markdown widget below with some basic explanations about what we are looking at.

**Comment by alpgarcia** [comment]
Please @mafesan take into account #314 to update this PR.

**Comment by mafesan** [comment]
Thank you for the heads-up @alpgarcia, 

I have updated both PRs, please review the changes.

**Comment by mafesan** [comment]
Please @alpgarcia, review both PR with the latest changes.

**Comment by alpgarcia** [comment]
LGTM, PRs merged, thnaks!
