### ISSUE TITLE
Explicity state what's the time unit for "Lead time" in Efficiency Help

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-sigils#314]
The files `github_issues_efficiency.json`, `json/gerrit_efficiency.json`, `json/github_pull_requests_efficiency.json` (and files proposed in #302 for Gitlab) have a string
`**Lead time**: the time between the initiation and completion of a production process, in this case, a review. Shown in average.`

As a user, in the web browser, I see numbers on the y axis like `200`, `400` but I do not know if those numbers are days or hours or minutes or something else. The help string above should explicitly cover this.

**Comment by alpgarcia** [comment]
Thanks @aklapper I'll take this into account before accepting GitLab panels and we'll fix this in future versions. Added to my queue :)

**Comment by mafesan** [comment]
I have submitted a PR which aims to address this issue: https://github.com/chaoss/grimoirelab-sigils/pull/318.

Best!
