### ISSUE TITLE
[chaoss-gmd][code_development] Build a panel for Maintainer Response to Merge Request Duration

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#323]
CHAOSS GMD working group has defined several metrics related to [code development efficiency](https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md#legacy-metrics-and-questions)

Taking `Maintainer Response to Merge Request Duration` metric definition from there, build a panel around this metric. Ideally, this panel should contain:
* No more than 5 widgets, to avoid overwhelming the user.
* A markdown widget below with some basic explanations about what we are looking at.

Pull Request Merged panel can be used as an example of the structure we would like to follow:
https://chaoss.github.io/grimoirelab-sigils/chaoss-gmd-cde/pull_requests_merged/

For more info on how to contribute, please read:
https://github.com/chaoss/grimoirelab-sigils/blob/master/CONTRIBUTING.md

**Comment by dicortazar** [comment]
According to the question in the wiki, this says: "What is the duration of time for a maintainer to make a first response to a code merge request?".

As a first step, we can simplify this analysis to measure the time to first response to a pull request.
