### ISSUE TITLE
Help usage messages in Demographics panel

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sigils#324]
Time picker in Demographics panel does not work because it doesn't use live data. Data are pre-calculated. It would be useful to add some kind of markdown box (like the ones in Efficiency panels) to inform about this issue. Otherwise, the behaviour of the panel would be weird.

**Comment by alpgarcia** [comment]
This should be solved by #330

**Comment by alpgarcia** [comment]
Closing it as #330 was already merged into master.
