### ISSUE TITLE
Gerrit-Backlog panel is displaying wrong list of organizations in the pie chart

### ISSUE THREAD

**Issue by dicortazar** [chaoss/grimoirelab-sigils#329]
How to reproduce this:
* Open the Gerrit - Backlog panel. Then compare the number of changesets in the pie chart for a given organization to the number of changesets in the Summary widget.

Those are different because in the pie chart the number of changesets should be only the changesets opened as this is filtered in the rest of the panel.

**Comment by alpgarcia** [comment]
Panel was fixed at the same time we added the bots filter, see: https://github.com/chaoss/grimoirelab-sigils/pull/373/commits/8325bc7170f9865085e01dc129a93e7ce3d758d7
