### ISSUE TITLE
Panel to show data from GitHub repository category

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sigils#341]
Repository category was added recently to Perceval and GELK. This category provides some stats obtained from GitHub repositories such the number of works or the times a repository has been stared:

https://github.com/chaoss/grimoirelab-elk/commit/8cf1fbf9369e18b8313c30adff5a1422e4644513

Create a panel containing this information.

Task related to: chaoss/grimoirelab#184

**Comment by alpgarcia** [comment]
Solved by #347
