### ISSUE TITLE
 Rename gitlab index pattern

### ISSUE THREAD

**Issue by dplanella** [chaoss/grimoirelab-sigils#356]
This is a follow up to https://gitlab.com/Bitergia/c/gitlab/support/issues/44#note_166532787

GitLab-specific panels use two index patterns in Kibiter:

- `gitlab` => points to a  `gitlab-issues_*` index
- `gitlab_merge_requests` => points to a `gitlab-mrs_*` index

The naming is confusing here, as it would seem that `gitlab` is a general index pattern that encompasses both issues and MRs. In reality, `gitlab` only points to the issues index.

For consistency's sake, the `gitlab` index pattern should probably be renamed to `gitlab_issues`, and the default panels be updated accordingly to use the new name.

**Comment by alpgarcia** [comment]
This issue is addressed by:
* #357 
* chaoss/grimoirelab-sirmordred#296

Currently `gitlab` stills exists as an alias, but no Sigils GitLab panels use it.

Next step would probably be removing `gitlab` alias and make sure anything is broken after that.

**Comment by alpgarcia** [comment]
> Next step would probably be removing `gitlab` alias and make sure anything is broken after that.

This PR should address it: https://github.com/chaoss/grimoirelab-sirmordred/pull/299

**Comment by valeriocos** [comment]
Closing this issue, since the PR chaoss/grimoirelab-sirmordred#299 has been merged. The next release will come with this change.
