### ISSUE TITLE
Merge Panel Collections into GrimoireLab Sigils

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab-sigils#372]
The goal of this task is to decommission the [Panel Collections repo](https://gitlab.com/Bitergia/panel-collections) and add the panels to [GrimoireLab Sigils](https://github.com/chaoss/grimoirelab-sigils).

Closing condition:
- [ ] add panels from Panel Collections repo to Sigils
- [ ] empty Panels Collections repo and leave a message on the README to forward people to sigils

**Comment by alpgarcia** [comment]
Closed via:
* https://github.com/chaoss/grimoirelab-sigils/pull/390
* https://gitlab.com/Bitergia/panel-collections/merge_requests/13

NOTE: panel collections was not emptied, README file and web page were updated instead to inform about the new location of the dashboards.
