### ISSUE TITLE
Update Jira panels to suport changes of chaoss/grimoirelab-elk#656

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#378]
After the changes of https://github.com/chaoss/grimoirelab-elk/issues/656 we need to update Jira panels to filter in items which `author_type` is `creator`.

Now items are replicated by `creator`, `reporter` and `assignee`, so we can decide whether we provide data from one or another at the same level, instead of having creators and assignees within the same item (which didn't allow to count both of them in a single bucket by `author_uuid` or `author_name`). This way we can use a single bucket to track all activity of a single author instead of having the need of showing that info in separate visualizations,

**Comment by sduenas** [comment]
Already fixed by #379
