### ISSUE TITLE
Add link to CHAOSS metric definition in bottom help section of each panel

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#386]
New panels contain a MarkDown text explaining some panel basics and pointing at panel documentation web page (the ones we have [here](https://chaoss.github.io/grimoirelab-sigils/)).

The goal of this issue will be adding a link either within the MarkDown widget or the documentation web page to the corresponding CHAOSS metric definition(s) shown in the dashboard.

**Comment by GeorgLink** [comment]
Both 👍 
- inside the panels
- in the Sigils description

**Comment by GeorgLink** [comment]
I change my mind: what ever is easiest and fastest.

**Comment by valeriocos** [comment]
After merging the PR #399, which includes info about the CHAOSS project and the corresponding metrics defined, we can close this issue.

@GeorgLink @alpgarcia feel free to reopen it if needed.
