### ISSUE TITLE
Evaluate removal of images at docs/assets/images

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-sigils#419]
It seems that the images at https://github.com/chaoss/grimoirelab-sigils/tree/master/docs/assets/images are not used anymore (the ones used in the documentation are at https://github.com/chaoss/grimoirelab-sigils/tree/master/docs/assets/images/screenshots). 

The goal of this issue is to delete them from the repo if possible.

**Comment by alpgarcia** [comment]
The problem with these images is they are linked from hidden documentation pages:
* https://chaoss.github.io/grimoirelab-sigils/fam/ (generated from https://github.com/chaoss/grimoirelab-sigils/blob/master/docs/fam.md)
* https://chaoss.github.io/grimoirelab-sigils/metrics/ (generated from https://github.com/chaoss/grimoirelab-sigils/blob/master/docs/metrics.md)
* https://chaoss.github.io/grimoirelab-sigils/dashboard-customization/ (generated from https://github.com/chaoss/grimoirelab-sigils/blob/master/docs/dashboard-customization.md)
* https://chaoss.github.io/grimoirelab-sigils/README/ (generated from https://github.com/chaoss/grimoirelab-sigils/blob/master/docs/README.md)

We should decide what we want to do with them too. Options are basically:
1. Removing everything.
2. Updating the web page to include these pages and updating the pages themselves.

I guess we would need to agree at least with @jsmanrique and @dicortazar.

My vote is for removing everything and having here only dashboard related documentation, by each dashboard. All these documents seem to me out of the scope of Sigils, that imho should be documenting the existing dashboards, provide guidelines for contributing and probably installing them on top of GrimoireLab data.

**Comment by valeriocos** [comment]
+1 for removing everything. These pages are not available at https://chaoss.github.io/grimoirelab-sigils/

**Comment by alpgarcia** [comment]
@jsmanrique also voted +1 to the removal, so @valeriocos updated #427 accordingly.

**Comment by alpgarcia** [comment]
Closing via #427
