### ISSUE TITLE
[Feature request] Add link to JSON file in a respective panel/dashboard documentation page

### ISSUE THREAD

**Issue by tivaliy** [chaoss/grimoirelab-sigils#442]
Currently Dashboard/Panel documentation pages (https://chaoss.github.io/grimoirelab-sigils/) do not contain any link to a respective `json` file. So it's rather tricky to define which one should be used with `kidash`. It'll be a great to have a direct link to `json` file on a Dashboard/Panel documentation page.

**Comment by alpgarcia** [comment]
Hi @tivaliy,

I've opened a draft PR (https://github.com/chaoss/grimoirelab-sigils/pull/457) to address this. It's just a simple example using the Git dashboard:
![Screenshot from 2020-07-09 17-25-26](https://user-images.githubusercontent.com/3502941/87063164-44edfe80-c20e-11ea-928c-5f833a23d754.png)

I wonder whether adding the specific kidash lines needed for importing the dashboard would be also useful.

Once we are all happy with the draft, I'll add it to the rest of the documentation pages.

(cc @GeorgLink @dicortazar @valeriocos @jsmanrique )

Best,
Alberto.

**Comment by GeorgLink** [comment]
Good idea :)

**Comment by jsmanrique** [comment]
LGTM

**Comment by tivaliy** [comment]
Looks good to me too.

**Comment by mafesan** [comment]
As a reference note, while I was reviewing PR #457 I realized [Slack schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/slack.csv) format was wrong, so I have submitted a PR fixing it: https://github.com/chaoss/grimoirelab-elk/pull/930.
