### ISSUE TITLE
Visualization with appropriate metrics in the Kibana Dashboard

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab-sigils#460]
Hello ,

I am using `https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml` for the execution of dashboard.

Question:
How can i see comments section in the dashbaord ?
I would like to know how can i create a table which gives visualisation of something as shown below:

https://user-images.githubusercontent.com/63613092/87487734-c397d100-c63e-11ea-93e4-bf34c8b1620d.png
I need to know the process to create this.

Thank you

**Comment by shikha0208** [comment]
Hi @zhquan ,

For this fields also ,
-> Organisation Member name who commented last on the issue (org_member_name)
-> How many comments the Organization member is behind after the issue raiser has commented ,count of that like 1 ,2 etc
-> How many comments the Organization member has given ,count of that.

I need to play around with these :
comment_updated_at: comment create date
issue_url: issue URL
is_github_comment: is a comment

It is bit confusing to understand the perfect match for these fields.
How can i get a` count on comment` which is not replied by the org member?

**Comment by alpgarcia** [comment]
Hi @shikha0208,

I'm sorry but I don't know which is the goal of this issue. The title says `Comments section Table in Dashboard is not displayed `. I don't know which dashboard you refer to. I would kindly suggest updating the title to something more focused on the goal you want to achieve. As it is written, it seems a bug on a specific dashboard, but I'd say this is not the case.

Best,
Alberto.

**Comment by alpgarcia** [comment]
> How can i get a count on comment which is not replied by the org member?

I would try to build an enhanced table:
* Bucket by issue id. This way you will group all comment documents together in the same bucket.
* Metric `Top Hit` to get the list of all the possible values of the `author_org_name`.
* Then configure the table to hide those rows containing the name of the org you wish in the corresponding column.
* You can also hide the column with the org names to get a cleaner table.
* If you want to exclude the issue itself, you could add a filter on top to filter in documents of comment type (https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github2_issues.csv#L33).

For more information on the enhanced table plugin you can check the official documentation:
https://github.com/fbaligand/kibana-enhanced-table

For more info on the available fields in GrimoireLab index:
https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github2_issues.csv

I would suggest you close this issue and open a new one detailing the use case you want to solve with this dashboard. It would be great to have your dashboard contributed to the project once you are happy with it. Having an issue with the specific use case details will help others to understand the problem and the solution, and will also be helpful for you to write the final dashboard documentation.

Thanks!
Alberto.

**Comment by shikha0208** [comment]
Hi @alpgarcia ,

Well, I sorted bucket with issue id and PFA but i could just see issue id's in the table.
https://user-images.githubusercontent.com/63613092/87786725-c19a6180-c83a-11ea-9fd0-87bda1fc6b89.png

For metrics , i sorted with `top hit `and` author org name`
PFA

https://user-images.githubusercontent.com/63613092/87786870-0625fd00-c83b-11ea-94b6-61263573793c.png

I didn't understand the columns hiding part.
Ok sure. i am closing this issue and opening new issue with specific details.

Thank you
