### ISSUE TITLE
New diagram request for contributions and authors by organization

### ISSUE THREAD

**Issue by Virkeipa** [chaoss/grimoirelab-sigils#464]
Hi,

It would be great to have a bar chart to see the contributions and authors by organization in the same graph, something similar to this attached file.Thank you!

![New_Diagram_authors_contributions_by_organization](https://user-images.githubusercontent.com/51788581/89405557-10416a00-d71c-11ea-8890-1e80d27a5130.png)

**Comment by alpgarcia** [comment]
This would be useful especially for [Affiliations](https://chaoss.github.io/grimoirelab-sigils/panels/affiliations/) dashboard.
