### ISSUE TITLE
Gerrit index pattern is missing `demography_*` fields

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#471]
There are no `demography_*` fields in the index pattern for Gerrit. This causes Kibana to hide the fields even if the study is active and the data in place in the index.

https://github.com/chaoss/grimoirelab-sigils/blob/9d6871823f951c10b2f0a004e2517bea9a979ad3/json/gerrit-index-pattern.json#L7

**Comment by mafesan** [comment]
@alpgarcia The PR fixing this issue is now available at https://github.com/chaoss/grimoirelab-sigils/pull/472, thanks!
