### ISSUE TITLE
How to import opensearch dashboards into grimoire lab opensearch dashboards instance

### ISSUE THREAD

**Issue by rwood-97** [chaoss/grimoirelab-sigils#512]
Hi,

Thanks for updating these dashboards to allow for use with opensearch.
Could you give us some guidance on how to import the dashboards? We tried with Kidash but it doesn't seem to work.

**Comment by jjmerchante** [comment]
Hi @rwood-97 ,

To import dashboards into OpenSearch, open the left menu and navigate to **Management** > **Dashboard Management**. On the new page, select **Saved Objects**. From there, you can manually import the dashboards by clicking the **Import** button.

Hope this helps!

**Comment by rwood-97** [comment]
Hi, thanks! Does it all have to be done manually? i.e. could we save the ndjson files somewhere and they'll be automatically pulled in?

**Comment by jjmerchante** [comment]
Sorry, Kidash currently doesn't work with the newest version of Kibana and OpenSearch, and GrimoireLab currently doesn't provide an automatic way to import the `ndjson` files.

**Comment by rwood-97** [comment]
ah okay, no worries. Thanks for your help :)
